<?xml version="1.0" encoding="utf-8"?><Database Name="Prueba1" Class="Datos1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-3538PPG;Initial Catalog=Prueba1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Prueba1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.usuarios" Member="usuarios">
    <Type Name="usuarios">
      <Column Name="UsuariosID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="roles_usuarios" Member="roles" ThisKey="RolID" OtherKey="RolID" Type="roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.personas" Member="personas">
    <Type Name="personas">
      <Column Name="PersonaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Documento" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RolesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="roles_personas" Member="roles" ThisKey="RolesID" OtherKey="RolID" Type="roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="roles">
      <Column Name="RolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreRol" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="roles_usuarios" Member="usuarios" ThisKey="RolID" OtherKey="RolID" Type="usuarios" />
      <Association Name="roles_personas" Member="personas" ThisKey="RolID" OtherKey="RolesID" Type="personas" />
    </Type>
  </Table>
</Database>